// Word lists for sync key generation.
// Format: adjective-noun-NNNN
// Both lists must be kept in sync with cloudflare-worker/sync-worker.js.

export const ADJECTIVES: readonly string[] = [
  // Colors & shades
  "amber", "amethyst", "ash", "auburn", "azure",
  "beige", "black", "blond", "blood", "bone", "bronze", "buff",
  "chalk", "charcoal", "chestnut", "cobalt", "copper", "coral", "cream", "crimson", "cyan",
  "ebony", "emerald",
  "fawn", "flax", "flint",
  "garnet", "gold", "golden", "graphite", "green", "grey",
  "hazel", "heather", "honey",
  "indigo", "ivory",
  "jade", "jasper", "jet",
  "khaki",
  "lavender", "lilac", "lime",
  "mahogany", "maroon", "mauve", "midnight", "mint", "mocha", "moss", "mulberry", "mustard",
  "navy",
  "obsidian", "ochre", "olive", "onyx", "opal",
  "peach", "pearl", "pine", "plum",
  "quartz",
  "red", "rose", "rouge", "ruby", "russet", "rust",
  "sage", "salmon", "sapphire", "scarlet", "sepia", "sienna", "silver", "slate", "smoke", "steel", "straw",
  "tan", "tawny", "teal", "thistle", "topaz",
  "umber",
  "vermilion", "violet",
  "white", "wine",

  // Simple one-syllable qualities
  "aged", "airy", "arid", "awake", "awed",
  "bare", "bleak", "blunt", "bold", "brash", "brave", "brief", "bright", "brisk", "broad",
  "calm", "chill", "clear", "clean", "close", "cold", "cool", "crisp",
  "dark", "dear", "deep", "deft", "damp", "dim", "dry", "dull",
  "fair", "faint", "fast", "fine", "firm", "flat", "fond", "free", "fresh", "full",
  "glad", "good", "grand", "gray", "great", "grim",
  "hard", "hazy", "high", "huge",
  "keen", "kind",
  "late", "lean", "light", "long", "loud", "low", "lush",
  "mild", "mute",
  "neat", "new", "nice",
  "odd", "old",
  "pale", "pink", "plain", "pure",
  "quick", "quiet",
  "rare", "raw", "real", "rich", "ripe", "rough", "round",
  "safe", "sharp", "shy", "slim", "slow", "small", "soft", "sole", "spare", "still", "stout", "sure", "swift",
  "tall", "tame", "taut", "thin", "tight", "tough", "true", "trim",
  "vast",
  "warm", "wide", "wild", "wise", "worn",

  // Weather & nature descriptors
  "alpine", "ancient", "ashen",
  "barren", "blazing", "breezy", "briny",
  "chilly", "cloudy", "coastal",
  "dewy", "distant", "dusty",
  "earthy", "elder", "endless", "evergreen",
  "fading", "fallow", "feral", "flowing", "foggy", "forested", "frozen",
  "gentle", "gilded", "glacial", "glowing", "grassy",
  "hollow", "humble",
  "icy",
  "jagged",
  "leafy", "lofty", "lunar",
  "marble", "marshy", "misty", "mossy", "mountain", "muddy", "murky",
  "narrow", "native",
  "ocean", "olden", "outer",
  "pearly", "piney", "placid", "polar",
  "rainy", "rapid", "rocky", "rooted", "rosy", "royal", "rugged", "rural", "rustic", "rustling",
  "sandy", "serene", "shaded", "silent", "sleek", "slender", "smoky", "snowy", "solemn", "sparkling", "stony", "stormy", "summer", "sunlit", "sunny",
  "tangled", "tidal", "timeless", "towering",
  "verdant", "vivid",
  "watery", "wintry", "woodland", "woody",

  // Character & feeling
  "agile", "ample", "ardent", "attentive",
  "balanced", "boundless",
  "candid", "careful", "clever", "common", "cunning",
  "dapper", "daring", "devoted", "durable",
  "earnest", "faithful", "famous", "fierce", "forceful",
  "gallant", "graceful", "grateful",
  "hallowed", "healing", "hefty", "honest", "hopeful", "hushed",
  "jolly", "joyful", "joyous",
  "kindly", "knowing",
  "languid", "lasting", "lively", "loyal",
  "majestic", "mellow", "merciful", "modest",
  "patient", "peaceful", "poised", "proud", "primal", "proven",
  "radiant", "resolute", "restful", "rising", "rolling",
  "sacred", "seasonal", "settled", "simple", "skilled", "sober", "soaring", "solid", "stable", "steady", "sterling", "stoic", "striking", "sturdy", "subtle",
  "tender", "tranquil", "trusty", "twisted",
  "vibrant", "worthy", "young",

  // Texture & appearance
  "aglow", "baked", "bonny", "bountiful", "braided", "brazen", "burnished",
  "carved", "chiseled", "compact", "crystal",
  "dappled", "dauntless", "dense",
  "elegant", "enduring",
  "flinty", "fluid", "flushed", "focused",
  "gnarled", "gradual", "gritty", "grounded",
  "hammered", "hardy", "harmonious", "hewn", "hidden",
  "knotted",
  "layered", "lithe", "lucid", "luminous",
  "measured", "molten", "motionless",
  "nimble", "orderly",
  "pebbled", "pewter",
  "refined", "resonant", "restless", "robust",
  "sculpted", "sheltered", "shining", "smooth", "solitary", "sparse", "spirited", "spreading",
  "staunch", "sunken", "supple",
  "textured", "thorny", "tidy", "timely", "turbid",
  "uncut", "unhurried", "untamed", "upland",
  "wandering", "weathered", "winding",
  "yielding",

  // Further descriptors
  "ablaze", "abundant", "active", "acute", "adept", "adroit", "aerial", "ageless",
  "benign", "blessed", "blithe",
  "capable", "commanding", "complete", "constant", "contented", "cordial",
  "decisive", "defined", "delicate", "dependable", "direct",
  "eager", "elevated", "eminent", "evident",
  "fertile", "fitting", "fixed", "flexible", "forthright", "fulfilled",
  "genuine", "glassy", "glinting", "guiding",
  "hearty", "helpful",
  "limpid", "local", "logical",
  "metered", "mighty", "mindful", "moderate",
  "nascent", "natural", "nearby", "nurtured",
  "open", "ordered", "outward",
  "perfect", "planted", "plentiful", "precise", "present",
  "ready", "reliable",
  "seasoned", "secure", "soothing", "stalwart", "standing", "steadfast", "straight", "strong", "sunward",
  "tested", "thorough", "toned",
  "undaunted", "unfailing",
  "vigorous", "visible",
  "watchful", "wholesome",
];

export const NOUNS: readonly string[] = [
  // Landscape & terrain
  "arch", "arroyo", "atoll", "bank", "basin", "bay", "beck", "bend", "bight", "bluff",
  "bog", "brae", "brook", "butte",
  "cairn", "canyon", "cape", "cave", "channel", "cliff", "coast", "col", "combe", "crag", "crest",
  "dale", "dam", "dell", "den", "dune",
  "edge", "estuary",
  "falls", "fen", "firth", "fjord", "ford", "gap", "gate", "gill", "glade", "glen",
  "gorge", "grove", "gulf", "gully",
  "haugh", "haven", "heath", "height", "hill", "hillock", "hollow",
  "inlet", "isle",
  "knoll",
  "lagoon", "lake", "lea", "ledge", "loch", "lowland",
  "marsh", "meadow", "mesa", "mire", "moor", "mount", "mouth",
  "neck", "nook", "notch",
  "ocean", "pass", "path", "peak", "plain", "plateau", "pond", "pool", "prairie",
  "ravine", "reef", "ridge", "rill", "rise", "river", "rock", "runnel",
  "scarp", "sea", "shelf", "shore", "shoal", "slope", "sound", "spit", "spring", "spur", "strand", "stream",
  "summit", "surf", "swamp", "swell",
  "tarn", "terrace", "tide", "tor", "torrent", "trail",
  "vale", "valley",
  "wash", "wave", "weald", "weir", "well", "wetland", "wood",

  // Water features
  "brine", "burn", "current", "dew", "drift", "eddy", "flood", "foam", "floe",
  "frost", "haze", "ice", "melt", "mere", "mist", "moat", "rain", "snow",

  // Plants & trees
  "acorn", "alder", "ash", "bark", "beech", "birch", "blossom", "bloom", "bough", "bracken", "briar", "broom", "brush",
  "bulb", "bulrush", "burdock",
  "cane", "catkin", "cedar", "clover", "cone",
  "dock", "elder", "elm",
  "fern", "fir", "flax", "flower", "frond", "furze",
  "gorse", "grass", "hay", "hazel", "hedge", "herb", "holly", "hops", "hull",
  "ivy",
  "kelp",
  "larch", "leaf", "lichen", "lime",
  "maple", "mint", "moss", "mushroom", "myrtle",
  "nettle",
  "oak", "orchard", "osier",
  "palm", "petal", "pine", "plum",
  "reed", "root", "rose", "rush", "rye",
  "sage", "sapling", "sedge", "seed", "shrub", "sorrel", "sprig", "stem", "stump",
  "thistle", "thorn", "thyme", "timber", "tinder", "tuber", "turf", "twig",
  "vine",
  "wheat", "willow", "woad", "wort",
  "yew",

  // Animals, birds & fish
  "adder", "badger", "bass", "bear", "bittern", "bird", "boar", "bream", "buck", "bull", "bunting",
  "carp", "chub", "colt", "crane", "crow", "curlew",
  "dace", "deer", "dove", "drake", "duck",
  "eagle", "elk", "emu",
  "falcon", "fawn", "finch", "flock", "fox",
  "gannet", "goose", "grouse", "gull",
  "hare", "hawk", "heron", "hind",
  "ibis",
  "jackdaw", "jay",
  "kite", "kiwi",
  "lamb", "lark", "linnet", "lion", "loon", "lynx",
  "magpie", "mallard", "mare", "marten", "martin", "mink", "moorhen", "moose", "moth",
  "newt", "nuthatch",
  "osprey", "otter", "owl",
  "perch", "pike", "pigeon", "plover", "puffin",
  "quail",
  "raven", "redstart", "robin", "roach", "rook",
  "skylark", "snake", "snipe", "sparrow", "stag", "starling", "swan", "swift",
  "teal", "tench", "tern", "thrush", "toad", "trout",
  "viper", "vole",
  "wagtail", "wolf", "wren",

  // Sky, weather & elements
  "arc", "blaze", "bolt", "chill",
  "chalk", "charcoal", "clay", "cloud", "coal", "cinder", "cobble", "comet", "copper", "crystal",
  "dawn", "dust", "dusk",
  "ember",
  "flint", "flame", "fog",
  "gale", "glass", "glow", "gold", "granite", "gravel", "grit", "gust",
  "hail", "heat",
  "iron",
  "lode", "light",
  "marble", "marl", "mica",
  "moon", "morning",
  "night", "nova",
  "opal", "ore",
  "peat", "quartz",
  "ray", "salt", "sand", "schist", "shade", "shadow", "silt", "sky", "slate",
  "sleet", "smog", "smoke", "soot", "spar", "spark", "star", "steam", "steel", "stone", "storm", "sun",
  "thunder", "twilight",
  "vapor", "veil", "wind", "wisp",

  // More geological
  "agate", "basalt", "calcite", "limestone", "shale",

  // Structures & built features
  "axe", "blade", "bridge", "ditch", "grange", "pebble", "pier", "quay", "rampart", "tower", "wall",

  // Natural features & objects
  "acre", "alp", "anchor", "antler", "anvil", "apex", "arbor", "arena", "ascent", "aspect",
  "beacon", "bed", "belt", "bench", "berm", "bill", "border", "bower", "bramble", "branch",
  "brim", "brink", "brow", "burrow",
  "cap", "chasm", "chimney", "clearing", "cleft", "cluster", "cord", "covert", "cradle", "croft", "crown",
  "depth", "descent", "dome", "draw", "drove", "drum",
  "face", "field", "flare", "floor", "fold", "front", "fringe",
  "gash", "gem", "girth", "gloom", "grain", "growth",
  "hamlet", "haunt", "head", "hearth", "helm", "herd", "holt", "horn",
  "kern", "knob",
  "layer", "loft", "lodge", "loop",
  "mark", "mass", "mill", "mound",
  "node",
  "orb", "outpost",
  "pace", "plume", "point", "port",
  "quarter",
  "range", "realm", "ring", "road",
  "seat", "seam", "side", "sill", "span", "spire", "stalk",
  "vault", "vein", "verge", "view",
  "ward", "yard", "zone",
];

export function validateWordPair(words: string): { valid: boolean; error?: string } {
  const parts = words.trim().split("-");
  if (parts.length !== 2) {
    return { valid: false, error: "Enter exactly two words separated by a hyphen (e.g. amber-forest)." };
  }
  for (const w of parts) {
    if (!/^[a-z]+$/.test(w)) {
      return { valid: false, error: "Words must contain only letters (a–z), no spaces or numbers." };
    }
    if (w.length < 2 || w.length > 20) {
      return { valid: false, error: "Each word must be between 2 and 20 letters." };
    }
  }
  return { valid: true };
}
